[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.build]
# We add a check to see where the output actually went
cmds = ["npm ci", "npm run build", "ls -R .output"] 

[start]
# We use ./app/.output to be absolutely certain of the path
cmd = "NODE_ENV=production HOST=0.0.0.0 PORT=3000 node /app/.output/server/index.mjs"